### ISSUE TITLE
It seems that notifyByQuery method with 'inq' operator didn't work 

### ISSUE THREAD

**Issue by jingood2** [strongloop/loopback-component-push#81]
I tried to send a notification to devices with specified userId. 
But It seems that notifyByQuery method with 'inq' operator didn't work. 
I don't know what it wrong with filter string. 

For checking 'notifyByQuery', I modified filter in push-manager.js as below. 

``` js
PushManager.prototype.notifyByQuery = function(installationQuery, notification, cb) {
  assert.ok(cb, 'callback should be defined');
  var self = this;
  var list = [];

  list.push('553dbde51da38a1a0bfc2f8c');
  list.push('553dc6bb8bf8f63a0e99039a');

 //var filter = { where: installationQuery};

// Query success
var filter = { where: { userId: '553dbde51da38a1a0bfc2f8c'}};

// Empty result
var filter = { where: {userId: {inq: list} } };
var filter = { where : { userId: {inq: [ '553dbde51da38a1a0bfc2f8c','553dc6bb8bf8f63a0e99039a' ]}}};
```

**Comment by raymondfeng** [comment]
I believe your database is MongoDB. Can you try to wrap the user ids as ObjectId?

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by bajtos** [comment]
@jingood2 is this issue still relevant? Could you please try the workaround proposed by @raymondfeng above?

**Comment by koppulapr** [comment]
This is still an issue, does anybody have a solution.

**Comment by koppulapr** [comment]
Tried the workaround but still facing the same issue.

**Comment by tekand** [comment]
@bajtos @raymondfeng 

I also had the same issue (still have actually). But I found a workaround.
I think the issue is caused by where clause added in the following line:
https://github.com/strongloop/loopback-component-push/blob/master/lib/push-manager.js#L251

It works as expected, if I delete this manually and assign the `installationQuery` directly to the `filter` variable.

**Comment by eperico** [comment]
@bajtos @raymondfeng 
I got the same problem as you and it works find after applying @tekand fix.

Do we know how this fix is not included in the latest release? Is there another workaround?

**Comment by felipetoffolo1** [comment]
+1

**Comment by bajtos** [comment]
Hello, quoting https://github.com/strongloop/loopback-component-push/pull/104#issuecomment-240418326
> To be honest, this change doesn't make sense to me. The only way I can see this may work is by creating an invalid filter that matches all records because it's missing a `where` clause (`filter = { userId: ... }`).

> Having wrote that, if `notifyByQuery` does not work, then it's definitely something to fix. The issue #81 seems to describe a problem specific to MongoDB and the way how it treats ObjectID values passed as strings.

> My impression is that we still don't fully understand what is the root cause of the problem. Let's close this pull request and move the discussion back to #81 please.

We need your help to move this forward: either create a unit-test reproducing the issue or provide us with a sandbox app that does reproduce it, see https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

Also please check whether the bug is present when using a different database than MongoDB, for example the built-in memory storage.

**Comment by yugidazai** [comment]
Actually the workaround does not work.
In fact, without a `where` clause, the `find` method of the Installation model ignores the query and returns all installations, hence notifies to all devices stored in DB.
That's why we thought it worked.

The problem is due to the `find` method in 
`var self = this;
  var filter = { where: installationQuery };
  self.Installation.find(filter, function(err, installationList) {
    if (err) return cb(err);`
It does not work with `inq` operator.

Any help???

**Comment by iMone** [comment]
Hi everyone! I came across the same issue and solved adding:

`"options": {
     "strictObjectIDCoercion": true
}`

Inside the installation model definition.

**Reason:**
The mongodb connector automatically converts a given string to ObjectId when the string has the the same length and characteristics of a MongoDB ObjectId. So "notifyByQuery" search for userIds as they were ObjectIds and fails because they are strings. The above option avoid coercion of id-like strings to ObjectID types.
