### ISSUE TITLE
Loopback Push Component docs doesn't mention datasource.json

### ISSUE THREAD

**Issue by harshil93** [strongloop/loopback-component-push#92]
In the official docs (http://docs.strongloop.com/display/public/LB/Push+notifications) , it is not mentioned that one has to add a new datasource for push notification. I only found out this after reading the example file by file.

**Comment by clarkbw** [comment]
This should be fixed by #87

**Comment by crandmck** [comment]
I finally got a chance to update that doc.  It now mentions `datasources.json` at least.  I think it could be further improved, but I'm going to close this issue, since this specific item is addressed.  Please add any further doc suggestions in https://github.com/strongloop/loopback-component-push/issues/87.
